name: Jira Issues into Markdown
description: Jira Action to obtain data from Issues and pass it to markdown
author: iamigui

branding:
  color: orange
  icon: play-circle

runs:
  using: 'node20'
  main: 'dist/index.js'
