name: Jira Issues into Markdown
description: Jira Action to obtain data from Issues and pass it to markdown
author: iamigui

branding:
  color: black
  icon: play-circle

inputs:
  branch_name:
    description: Branch name
    required: true
    default: ""

runs:
  using: "node20"
  main: "dist/index.js"
