name: Tag and Release in Github

on:
  push:
    branches:
      - feature/*
      - release/*
      - fix/*
  pull_request:
    types: [closed]

permissions:
  contents: write # Grant permission to write to the repository

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        shell: bash
        run: |
          git config user.name "gh-actions-releaser"
          git config user.email "ghactionsreleaser@gmail.com"

      - name: Get tag
        shell: bash
        id: get_tag
        run: |
          git fetch --all

          if [ -z "${{ github.event.pull_request.head.ref }}" ]; then
            echo "branch=${{ github.ref }}" >> $GITHUB_OUTPUT 
          else
            git checkout ${{ github.event.pull_request.head.ref }}
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT 
          fi
          echo "version=v$(npm pkg get version | tr -d '\"')" >> $GITHUB_OUTPUT

      - name: Tag the commit
        if: ${{ github.event.pull_request.merged == true }}
        shell: bash
        run: |
          next_version=${{ steps.get_tag.outputs.version }}
          git tag $next_version
          git push origin $next_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mask secrets
        id: mask_secrets
        uses: actions/github-script@v7
        with:
          script: |
            const jira_data = `${{ secrets.JIRA_DATA }}` || '{}';
              
            const data = JSON.parse(jira_data);

            try {
              core.setSecret(data.api_token);
              core.setSecret(data.email);
              core.setSecret(data.domain);
              core.setSecret(data.project_key);
            } catch (error) {
              core.setFailed(`'jira_data' should be a valid JSON`)
            }

      - name: Launch Jira Tasks
        id: jira_tasks
        uses: iamigui/jira-issue-to-markdown@main
        env:
          BRANCH_NAME: ${{ steps.get_tag.outputs.branch }}
          JIRA_API_TOKEN: ${{ fromJSON(secrets.JIRA_DATA).api_token }}
          JIRA_EMAIL: ${{ fromJSON(secrets.JIRA_DATA).email }}
          JIRA_DOMAIN: ${{ fromJSON(secrets.JIRA_DATA).domain }}
          JIRA_PROJECT_KEY: ${{ fromJSON(secrets.JIRA_DATA).project_key }}

      - name: Get Outputs
        id: get_release_notes
        shell: bash
        run: |
          echo "Release content from the previous step:"
          cat RELEASE_NOTES.md
          echo "::set-output name=release_content::$(cat RELEASE_NOTES.md)"

      - name: Release
        id: release
        shell: bash
        if: ${{ github.event.pull_request.merged == true }}
        run: |
          TAG_NAME=${{ steps.get_tag.outputs.version }}
          PR_DESCRIPTION="${{ steps.get_release_notes.outputs.release_content }}"
          echo "Creating release for tag: $TAG_NAME"
          echo "Description: $PR_DESCRIPTION"
              
          # Create the release with the PR description
          gh release create $TAG_NAME --title "$TAG_NAME" --notes "$PR_DESCRIPTION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
